name: HGGodWars
main: org.bitbucket.platky.HGGodWars.HGGodWars
version: 0.0.1
author: Platky
commands:
    godwars:
        description: Main HGGodWars command
    karma:
        description: Main karma command from HGGodWars